version: ~> 1.0
import: collective/buildout.plonetest:travis/default.yml
jobs:
  include:
  - python: "2.7"
    env: PLONE_VERSION=5.0
  - python: "2.7"
    env: PLONE_VERSION=5.1
  - python: "2.7"
    env: PLONE_VERSION=5.2
  - python: "3.7"
    env: PLONE_VERSION=5.2
